version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.4
  node: circleci/node@0.0.4
  slack: circleci/slack@0.1.0

common-build-steps: &common-build-steps
  steps:
    - checkout
    - attach_workspace:
        at: .
    - node/install-package-manager:
        npm: true
    - run:
        name: Install Dependencies
        command: npm install --production
    - run:
        name: Build
        command: NODE_ENV=${NODE_ENV} REACT_APP_ENV=${NODE_ENV} npm run build
    - persist_to_workspace:
        root: .
        paths:
          - static

common-release-steps: &common-release-steps
  steps:
    - aws-cli/install
    - attach_workspace:
        at: .
    - run:
        name: Install and Deploy to S3
        command: >
          aws s3 sync ./build s3://${AWS_S3_BUCKET} 
          --delete 
          --exclude ".*" 
          --acl public-read 
          --cache-control cacheHeader="public, max-age=${MAX_AGE}"

jobs:

  build-dev:
    executor: node/default
    environment:
      NODE_ENV: development
    <<: *common-build-steps

  release-dev:
    executor: aws-cli/default
    environment:
      AWS_S3_BUCKET: www.dev.carclub.com
      MAX_AGE: 60
    <<: *common-release-steps

  build-stage:
    executor: node/default
    environment:
      NODE_ENV: staging
    <<: *common-build-steps

  release-stage:
    executor: aws-cli/default
    environment:
      AWS_S3_BUCKET: www.stage.carclub.com
      MAX_AGE: 1800
    <<: *common-release-steps

  build-prod:
    executor: node/default
    environment:
      NODE_ENV: production
    <<: *common-build-steps

  release-prod:
    executor: aws-cli/default
    environment:
      AWS_S3_BUCKET: www.carclub.com
      MAX_AGE: 3600
    <<: *common-release-steps

workflows:
  version: 2
  deployment:
    jobs:
    - build-dev:
        context: carclub-dev
        filters:
          branches:
            only:
            - develop
    - release-dev:
        requires:
          - build-dev
        context: carclub-dev
        filters:
          branches:
            only:
            - develop
    - build-stage:
        context: carclub-stage
        filters:
          branches:
            only:
            - /^release\/.*$|^hotfix\/.*$/
    - release-stage:
        requires:
          - build-stage
        context: carclub-stage
        filters:
          branches:
            only:
            - /^release\/.*$|^hotfix\/.*$/
    - build-prod:
        context: carclub-prod
        filters:
          branches:
            only:
            - master
    - release-prod:
        requires:
          - build-prod
        context: carclub-prod
        filters:
          branches:
            only:
            - master
